[2022-12-07T19:17:22.169+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.refresh_materialized manual__2022-12-07T19:17:08.290866+00:00 [queued]>
[2022-12-07T19:17:22.190+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.refresh_materialized manual__2022-12-07T19:17:08.290866+00:00 [queued]>
[2022-12-07T19:17:22.191+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T19:17:22.192+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-07T19:17:22.192+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T19:17:22.212+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): refresh_materialized> on 2022-12-07 19:17:08.290866+00:00
[2022-12-07T19:17:22.218+0000] {standard_task_runner.py:55} INFO - Started process 5572 to run task
[2022-12-07T19:17:22.223+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'refresh_materialized', 'manual__2022-12-07T19:17:08.290866+00:00', '--job-id', '1873', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpywwlv5gn']
[2022-12-07T19:17:22.224+0000] {standard_task_runner.py:83} INFO - Job 1873: Subtask refresh_materialized
[2022-12-07T19:17:22.316+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.refresh_materialized manual__2022-12-07T19:17:08.290866+00:00 [running]> on host a9d6893ff63e
[2022-12-07T19:17:22.427+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=refresh_materialized
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T19:17:08.290866+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T19:17:08.290866+00:00
[2022-12-07T19:17:22.442+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-12-07T19:17:22.453+0000] {sql.py:315} INFO - Running statement: REFRESH MATERIALIZED VIEW predictions
        , parameters: None
[2022-12-07T19:17:22.456+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "predictions" does not exist

[2022-12-07T19:17:22.472+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dag, task_id=refresh_materialized, execution_date=20221207T191708, start_date=20221207T191722, end_date=20221207T191722
[2022-12-07T19:17:22.493+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1873 for task refresh_materialized (relation "predictions" does not exist
; 5572)
[2022-12-07T19:17:22.516+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-07T19:17:22.539+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
