[2022-12-07T06:33:02.266+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T06:32:56.936724+00:00 [queued]>
[2022-12-07T06:33:02.281+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T06:32:56.936724+00:00 [queued]>
[2022-12-07T06:33:02.281+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T06:33:02.282+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-07T06:33:02.282+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T06:33:02.302+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): pull_data> on 2022-12-07 06:32:56.936724+00:00
[2022-12-07T06:33:02.307+0000] {standard_task_runner.py:55} INFO - Started process 25711 to run task
[2022-12-07T06:33:02.311+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'pull_data', 'manual__2022-12-07T06:32:56.936724+00:00', '--job-id', '1344', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp3653761l']
[2022-12-07T06:33:02.312+0000] {standard_task_runner.py:83} INFO - Job 1344: Subtask pull_data
[2022-12-07T06:33:02.510+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.pull_data manual__2022-12-07T06:32:56.936724+00:00 [running]> on host 505aa50095aa
[2022-12-07T06:33:02.664+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T06:32:56.936724+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T06:32:56.936724+00:00
[2022-12-07T06:33:02.682+0000] {logging_mixin.py:137} INFO - [['2022-12-07', 'USD', 'EUR', 0.95684871], ['2022-12-07', 'USD', 'RUB', 63.20365348], ['2022-12-07', 'EUR', 'RUB', 66.05396727]]
[2022-12-07T06:33:02.696+0000] {logging_mixin.py:137} INFO - Failed to insert into PostgreSQL
[2022-12-07T06:33:02.698+0000] {logging_mixin.py:137} INFO - relation "pairs" does not exist
LINE 1: INSERT INTO pairs VALUES('2')
                    ^
[2022-12-07T06:33:02.699+0000] {logging_mixin.py:137} INFO - CSSS
[2022-12-07T06:33:02.699+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-07T06:33:02.724+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=pull_data, execution_date=20221207T063256, start_date=20221207T063302, end_date=20221207T063302
[2022-12-07T06:33:02.770+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-07T06:33:02.794+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
