[2022-12-07T06:47:53.483+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T06:47:46.995375+00:00 [queued]>
[2022-12-07T06:47:53.508+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.pull_data manual__2022-12-07T06:47:46.995375+00:00 [queued]>
[2022-12-07T06:47:53.509+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T06:47:53.510+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-07T06:47:53.511+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T06:47:53.544+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): pull_data> on 2022-12-07 06:47:46.995375+00:00
[2022-12-07T06:47:53.551+0000] {standard_task_runner.py:55} INFO - Started process 26425 to run task
[2022-12-07T06:47:53.557+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'pull_data', 'manual__2022-12-07T06:47:46.995375+00:00', '--job-id', '1362', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmprrqslx4x']
[2022-12-07T06:47:53.558+0000] {standard_task_runner.py:83} INFO - Job 1362: Subtask pull_data
[2022-12-07T06:47:53.686+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.pull_data manual__2022-12-07T06:47:46.995375+00:00 [running]> on host 505aa50095aa
[2022-12-07T06:47:53.915+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=pull_data
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T06:47:46.995375+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T06:47:46.995375+00:00
[2022-12-07T06:47:53.946+0000] {logging_mixin.py:137} INFO - [['2022-12-07', 'USD', 'EUR', 0.95684871], ['2022-12-07', 'USD', 'RUB', 63.20365348], ['2022-12-07', 'EUR', 'RUB', 66.05396727]]
[2022-12-07T06:47:53.980+0000] {logging_mixin.py:137} INFO - Failed to insert into PostgreSQL
[2022-12-07T06:47:53.981+0000] {logging_mixin.py:137} INFO - relation "pairs" does not exist
LINE 1: INSERT INTO pairs VALUES('g')
                    ^
[2022-12-07T06:47:53.982+0000] {logging_mixin.py:137} INFO - CSSS
[2022-12-07T06:47:53.984+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-12-07T06:47:54.035+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag, task_id=pull_data, execution_date=20221207T064746, start_date=20221207T064753, end_date=20221207T064754
[2022-12-07T06:47:54.101+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-12-07T06:47:54.165+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
