[2022-12-07T14:50:27.247+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.refresh_materialized manual__2022-12-07T14:50:12.709258+00:00 [queued]>
[2022-12-07T14:50:27.264+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag.refresh_materialized manual__2022-12-07T14:50:12.709258+00:00 [queued]>
[2022-12-07T14:50:27.265+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T14:50:27.266+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-07T14:50:27.266+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-07T14:50:27.286+0000] {taskinstance.py:1383} INFO - Executing <Task(PostgresOperator): refresh_materialized> on 2022-12-07 14:50:12.709258+00:00
[2022-12-07T14:50:27.292+0000] {standard_task_runner.py:55} INFO - Started process 249 to run task
[2022-12-07T14:50:27.296+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag', 'refresh_materialized', 'manual__2022-12-07T14:50:12.709258+00:00', '--job-id', '1807', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpvjprbt3z']
[2022-12-07T14:50:27.297+0000] {standard_task_runner.py:83} INFO - Job 1807: Subtask refresh_materialized
[2022-12-07T14:50:27.377+0000] {task_command.py:376} INFO - Running <TaskInstance: dag.refresh_materialized manual__2022-12-07T14:50:12.709258+00:00 [running]> on host 20d9dd97c6ff
[2022-12-07T14:50:27.469+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=lofitravel
AIRFLOW_CTX_DAG_ID=dag
AIRFLOW_CTX_TASK_ID=refresh_materialized
AIRFLOW_CTX_EXECUTION_DATE=2022-12-07T14:50:12.709258+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-07T14:50:12.709258+00:00
[2022-12-07T14:50:27.480+0000] {base.py:71} INFO - Using connection ID 'postgres_localhost' for task execution.
[2022-12-07T14:50:27.491+0000] {sql.py:315} INFO - Running statement: REFRESH MATERIALIZED VIEW predictions
        , parameters: None
[2022-12-07T14:50:27.493+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 94, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: relation "predictions" does not exist

[2022-12-07T14:50:27.505+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dag, task_id=refresh_materialized, execution_date=20221207T145012, start_date=20221207T145027, end_date=20221207T145027
[2022-12-07T14:50:27.522+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1807 for task refresh_materialized (relation "predictions" does not exist
; 249)
[2022-12-07T14:50:27.548+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-12-07T14:50:27.569+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
